import type { Kategori } from "./daerah";

export type Entry = {
  id: string;
  kata: string;
  arti: string;
  daerah: string;
  contoh_kalimat?: string;
  kontributor?: string;
  ai_validated: boolean;
  ai_is_dialect?: boolean;
  ai_kategori?: Kategori;
  ai_catatan?: string;
  upvotes: number;
  created: string;
};

// 32 entri variasi 8+ daerah, 5 kategori, mix verified/menunggu
export const mockEntries: Entry[] = [
  // ============ JAWA (8 entri) ============
  {
    id: "ent_001",
    kata: "Matur Nuwun",
    arti: "Ungkapan terima kasih yang disampaikan dengan hormat, sering diiringi anggukan halus.",
    daerah: "Jawa",
    contoh_kalimat: "Matur nuwun sampun rawuh ing griya kula.",
    kontributor: "Aditya P.",
    ai_validated: true,
    ai_kategori: "ekspresi",
    upvotes: 128,
    created: "2026-07-20T10:00:00Z",
  },
  {
    id: "ent_002",
    kata: "Ayu",
    arti: "Cantik. Kata paling umum dipakai untuk mengagumi kecantikan seseorang.",
    daerah: "Jawa",
    contoh_kalimat: "Adhi kula ayu tenan.",
    kontributor: "Rina M.",
    ai_validated: true,
    ai_kategori: "kata benda",
    upvotes: 87,
    created: "2026-07-18T14:20:00Z",
  },
  {
    id: "ent_003",
    kata: "Endah",
    arti: "Indah, biasanya untuk pemandangan atau keindahan yang lebih puitis.",
    daerah: "Jawa",
    contoh_kalimat: "Pemandangan gunung Merapi punika endah sanget.",
    kontributor: "Bagas N.",
    ai_validated: true,
    ai_kategori: "kata benda",
    upvotes: 54,
    created: "2026-07-15T08:00:00Z",
  },
  {
    id: "ent_004",
    kata: "Mangan",
    arti: "Makan. Kata kerja dasar untuk aktivitas mengonsumsi makanan.",
    daerah: "Jawa",
    contoh_kalimat: "Mangga mangan sesarengan.",
    kontributor: "Aditya P.",
    ai_validated: true,
    ai_kategori: "kata kerja",
    upvotes: 41,
    created: "2026-07-14T12:00:00Z",
  },
  {
    id: "ent_005",
    kata: "Sinau",
    arti: "Belajar. Aktivitas menuntut ilmu atau mendalami sesuatu.",
    daerah: "Jawa",
    contoh_kalimat: "Kula badhe sinau basa Jawi.",
    kontributor: "Bu Sari",
    ai_validated: true,
    ai_kategori: "kata kerja",
    upvotes: 33,
    created: "2026-07-12T09:30:00Z",
  },
  {
    id: "ent_006",
    kata: "Ojo Dumeh",
    arti: "Jangan mentang-mentang. Peribahasa yang menasihati untuk tidak sombong.",
    daerah: "Jawa",
    contoh_kalimat: "Ojo dumeh dadi bos, kudu tetep rendah hati.",
    kontributor: "Pak Warto",
    ai_validated: true,
    ai_kategori: "peribahasa",
    upvotes: 92,
    created: "2026-07-10T16:00:00Z",
  },
  {
    id: "ent_007",
    kata: "Njajal",
    arti: "Mencoba. Melakukan sesuatu untuk pertama kali sebagai uji coba.",
    daerah: "Jawa",
    contoh_kalimat: "Ayo njajal panganan iki.",
    ai_validated: false,
    upvotes: 12,
    created: "2026-07-28T11:00:00Z",
  },
  {
    id: "ent_008",
    kata: "Ndalem",
    arti: "Rumah dalam bentuk halus dan hormat, biasanya untuk rumah orang lain.",
    daerah: "Jawa",
    kontributor: "Bagas N.",
    ai_validated: false,
    upvotes: 8,
    created: "2026-07-29T09:00:00Z",
  },

  // ============ SUNDA (6 entri) ============
  {
    id: "ent_009",
    kata: "Nuhun",
    arti: "Terima kasih. Ungkapan syukur dan apresiasi dalam Bahasa Sunda.",
    daerah: "Sunda",
    contoh_kalimat: "Nuhun pisan kana bantosanana.",
    kontributor: "Rina M.",
    ai_validated: true,
    ai_kategori: "ekspresi",
    upvotes: 76,
    created: "2026-07-19T13:00:00Z",
  },
  {
    id: "ent_010",
    kata: "Wilujeng Enjing",
    arti: "Selamat pagi. Sapaan hangat untuk mengawali hari.",
    daerah: "Sunda",
    contoh_kalimat: "Wilujeng enjing, sadayana.",
    kontributor: "Bu Sari",
    ai_validated: true,
    ai_kategori: "ekspresi",
    upvotes: 62,
    created: "2026-07-17T07:00:00Z",
  },
  {
    id: "ent_011",
    kata: "Geulis",
    arti: "Cantik dalam Bahasa Sunda. Sering dipakai memuji perempuan atau bunga.",
    daerah: "Sunda",
    contoh_kalimat: "Bungaan di taman geulis pisan.",
    kontributor: "Aditya P.",
    ai_validated: true,
    ai_kategori: "kata benda",
    upvotes: 58,
    created: "2026-07-16T10:00:00Z",
  },
  {
    id: "ent_012",
    kata: "Neda",
    arti: "Makan dalam bentuk halus. Dipakai saat menawarkan kepada tamu atau orang dihormati.",
    daerah: "Sunda",
    contoh_kalimat: "Mangga neda heula.",
    kontributor: "Bu Sari",
    ai_validated: true,
    ai_kategori: "kata kerja",
    upvotes: 24,
    created: "2026-07-11T14:00:00Z",
  },
  {
    id: "ent_013",
    kata: "Kadeudeuh",
    arti: "Kesayangan atau yang tercinta. Ungkapan sayang untuk orang terdekat.",
    daerah: "Sunda",
    ai_validated: false,
    upvotes: 15,
    created: "2026-07-27T15:00:00Z",
  },
  {
    id: "ent_014",
    kata: "Cageur Bageur",
    arti: "Sehat dan baik. Ungkapan doa dan harapan untuk keadaan seseorang.",
    daerah: "Sunda",
    contoh_kalimat: "Mugi salawasna cageur bageur.",
    kontributor: "Rina M.",
    ai_validated: true,
    ai_kategori: "peribahasa",
    upvotes: 38,
    created: "2026-07-13T11:00:00Z",
  },

  // ============ MINANG (4 entri) ============
  {
    id: "ent_015",
    kata: "Alam Takambang Jadi Guru",
    arti: "Alam yang terbentang menjadi guru. Belajar dari kejadian di sekitar, bukan hanya dari buku.",
    daerah: "Minang",
    contoh_kalimat: "Kok indak dapek di buku, cubo caliak alam.",
    kontributor: "Rina M.",
    ai_validated: true,
    ai_kategori: "peribahasa",
    upvotes: 92,
    created: "2026-07-19T10:00:00Z",
  },
  {
    id: "ent_016",
    kata: "Bagalau",
    arti: "Bergerombol atau berkumpul ramai. Menggambarkan orang banyak berkerumun.",
    daerah: "Minang",
    contoh_kalimat: "Urang bagalau di pasa pagi tadi.",
    kontributor: "Pak Amran",
    ai_validated: true,
    ai_kategori: "kata kerja",
    upvotes: 34,
    created: "2026-07-16T08:00:00Z",
  },
  {
    id: "ent_017",
    kata: "Rancak",
    arti: "Bagus atau cantik dalam Bahasa Minang. Ungkapan pujian yang tulus.",
    daerah: "Minang",
    contoh_kalimat: "Rancak bana baju anak gadis tu.",
    kontributor: "Rina M.",
    ai_validated: true,
    ai_kategori: "kata benda",
    upvotes: 27,
    created: "2026-07-14T13:00:00Z",
  },
  {
    id: "ent_018",
    kata: "Marantau",
    arti: "Meninggalkan kampung halaman untuk mencari penghidupan lebih baik.",
    daerah: "Minang",
    ai_validated: false,
    upvotes: 19,
    created: "2026-07-26T09:00:00Z",
  },

  // ============ BALI (4 entri) ============
  {
    id: "ent_019",
    kata: "Canang",
    arti: "Wadah kecil dari daun kelapa berisi bunga dan dupa, untuk persembahyangan harian.",
    daerah: "Bali",
    contoh_kalimat: "Ibu meletakkan canang di depan pintu setiap pagi.",
    kontributor: "Wayan S.",
    ai_validated: true,
    ai_kategori: "kata benda",
    upvotes: 74,
    created: "2026-07-18T06:00:00Z",
  },
  {
    id: "ent_020",
    kata: "Om Swastiastu",
    arti: "Salam pembuka umat Hindu Bali, artinya semoga dalam keadaan baik.",
    daerah: "Bali",
    contoh_kalimat: "Om Swastiastu, semeton sami.",
    kontributor: "Wayan S.",
    ai_validated: true,
    ai_kategori: "ekspresi",
    upvotes: 68,
    created: "2026-07-17T09:00:00Z",
  },
  {
    id: "ent_021",
    kata: "Melasti",
    arti: "Upacara penyucian menjelang Nyepi, dilakukan di laut atau mata air.",
    daerah: "Bali",
    kontributor: "Wayan S.",
    ai_validated: true,
    ai_kategori: "kata benda",
    upvotes: 45,
    created: "2026-07-15T15:00:00Z",
  },
  {
    id: "ent_022",
    kata: "Suksma",
    arti: "Terima kasih dalam Bahasa Bali. Ucapan syukur yang tulus.",
    daerah: "Bali",
    contoh_kalimat: "Suksma antuk bantuan bapak.",
    ai_validated: false,
    upvotes: 11,
    created: "2026-07-28T10:00:00Z",
  },

  // ============ BATAK (3 entri) ============
  {
    id: "ent_023",
    kata: "Horas",
    arti: "Sapaan hangat khas Batak yang berarti selamat, sejahtera.",
    daerah: "Batak",
    contoh_kalimat: "Horas ma di hita sude.",
    kontributor: "Ratu Fajar",
    ai_validated: true,
    ai_kategori: "ekspresi",
    upvotes: 89,
    created: "2026-07-18T07:00:00Z",
  },
  {
    id: "ent_024",
    kata: "Ulos",
    arti: "Kain tenun tradisional Batak, punya makna adat dalam berbagai upacara.",
    daerah: "Batak",
    kontributor: "Ratu Fajar",
    ai_validated: true,
    ai_kategori: "kata benda",
    upvotes: 52,
    created: "2026-07-14T11:00:00Z",
  },
  {
    id: "ent_025",
    kata: "Marsipature Hutanabe",
    arti: "Semangat gotong royong membangun kampung halaman bersama.",
    daerah: "Batak",
    ai_validated: false,
    upvotes: 21,
    created: "2026-07-27T14:00:00Z",
  },

  // ============ ACEH (3 entri) ============
  {
    id: "ent_026",
    kata: "Peuneulop",
    arti: "Bunga rampai atau taburan bunga wangi untuk upacara adat.",
    daerah: "Aceh",
    kontributor: "Pak Hasbi",
    ai_validated: true,
    ai_kategori: "kata benda",
    upvotes: 28,
    created: "2026-07-13T09:00:00Z",
  },
  {
    id: "ent_027",
    kata: "Peumulia Jamee",
    arti: "Memuliakan tamu. Falsafah hidup masyarakat Aceh dalam menyambut tamu.",
    daerah: "Aceh",
    contoh_kalimat: "Peumulia jamee adat geutanyoe.",
    kontributor: "Pak Hasbi",
    ai_validated: true,
    ai_kategori: "peribahasa",
    upvotes: 46,
    created: "2026-07-15T10:00:00Z",
  },
  {
    id: "ent_028",
    kata: "Meunasah",
    arti: "Bangunan tempat ibadah dan pertemuan warga di desa Aceh.",
    daerah: "Aceh",
    ai_validated: false,
    upvotes: 14,
    created: "2026-07-26T13:00:00Z",
  },

  // ============ BUGIS (2 entri) ============
  {
    id: "ent_029",
    kata: "Siri Na Pesse",
    arti: "Harga diri dan solidaritas. Nilai luhur masyarakat Bugis dalam bermasyarakat.",
    daerah: "Bugis",
    contoh_kalimat: "Siri na pesse iyanaritu poko-poko ade.",
    kontributor: "Andi P.",
    ai_validated: true,
    ai_kategori: "peribahasa",
    upvotes: 41,
    created: "2026-07-16T15:00:00Z",
  },
  {
    id: "ent_030",
    kata: "Sompa",
    arti: "Mahar atau maskawin dalam pernikahan adat Bugis.",
    daerah: "Bugis",
    ai_validated: false,
    upvotes: 9,
    created: "2026-07-28T12:00:00Z",
  },

  // ============ SASAK (1) + MADURA (1) ============
  {
    id: "ent_031",
    kata: "Tampiasih",
    arti: "Terima kasih dalam Bahasa Sasak Lombok. Ungkapan syukur yang halus.",
    daerah: "Sasak",
    contoh_kalimat: "Tampiasih, tuan haji.",
    kontributor: "Lalu Erwan",
    ai_validated: true,
    ai_kategori: "ekspresi",
    upvotes: 22,
    created: "2026-07-15T08:00:00Z",
  },
  {
    id: "ent_032",
    kata: "Sanaklah",
    arti: "Saudara atau kerabat. Ungkapan kekeluargaan dalam Bahasa Madura.",
    daerah: "Madura",
    contoh_kalimat: "Sanaklah kule kabbhi.",
    ai_validated: false,
    upvotes: 7,
    created: "2026-07-29T11:00:00Z",
  },
];

// ============ Data statistik (dipakai S5 dan chip count) ============
export const topKontributor = [
  { nama: "Aditya P.", jumlah_kata: 42, verified_pct: 92, daerah: "Jawa" },
  { nama: "Rina Maulida", jumlah_kata: 38, verified_pct: 87, daerah: "Minang" },
  { nama: "Wayan S.", jumlah_kata: 34, verified_pct: 94, daerah: "Bali" },
  { nama: "Pak Hasbi", jumlah_kata: 29, verified_pct: 89, daerah: "Aceh" },
  { nama: "Bu Sari", jumlah_kata: 26, verified_pct: 81, daerah: "Sunda" },
  { nama: "Bagas Nugroho", jumlah_kata: 22, verified_pct: 78, daerah: "Jawa" },
  { nama: "Ratu Fajar", jumlah_kata: 19, verified_pct: 84, daerah: "Batak" },
];
